### ISSUE TITLE
How to use `Value`

### ISSUE THREAD

**Issue by wusyong** [tauri-apps/javascriptcore-rs#42]
Hello, I updated the version flag on `webkit2gtk` recently and found `webkit2gtk::JavascriptResult` deprecated its previous 2 method and now suggest using `get_js_value` which return `Option<javascriptcore::Value>`.
But after I searching its doc, it doesn't have any method at all.
Whats the proper way to use it? Should I recast it to `ValueRef`?
![image](https://user-images.githubusercontent.com/8409985/126479624-999729f5-050d-49ec-b3a4-8fe5666d10f5.png)

**Comment by antoyo** [comment]
It seems like the [gir file](https://github.com/gtk-rs/gir-files/blob/master/JavaScriptCore-4.0.gir#L2538) of this library could now be used to auto-generate the Rust code using gir as it seems to contain everything needed.

I don't have much time to do this right now, but if somewant wants to make a PR, I'll accept it!
